<!-- footer section -->
<footer class="footersection">
  <div class="footercontainer d-flex">
    <div class="help footerbox">
      <p>Help & Contact</p>
      <div class="linkbox d-flex">
        <ul class="footerlink">
          <li><a href="#">About Us</a></li>
          <li><a href="#">Terms & Conditions</a></li>
          <li><a href="#">Branding Methods</a></li>
        </ul>
        <ul class="footerlink">
          <li><a href="#">Privacy Disclaimer</a></li>
          <li><a href="#">Artwork Guidelines</a></li>
          <li><a href="#">Reviews</a></li>
        </ul>
      </div>
    </div>

    <div class="category footerbox">
      <p>Categories</p>
      <div class="linkbox d-flex">
        <ul class="footerlink">
          <li><a href="#">Writing Instruments</a></li>
          <li><a href="#">Umbrellas And Ponchos</a></li>
          <li><a href="#">Apron & caps</a></li>
        </ul>
        <ul class="footerlink">
          <li><a href="#">Bags</a></li>
          <li><a href="#">Personal Items</a></li>
          <li><a href="#">Office Items</a></li>
        </ul>
        <ul class="footerlink">
          <li><a href="#">Technology</a></li>
          <li><a href="#">Trade Show And Events</a></li>
          <li><a href="#">Overseas Sourcing</a></li>
        </ul>
      </div>
    </div>

    <div class="footerservice footerbox">
      <div class="row">
        <div class="col">
          <p>Our Courier Services</p>
          <img
            src="https://idirectpromo.24livehost.com/front/img/courier.png"
            alt="footerservicepic"
          />
        </div>
        <div class="col">
          <p>Easy Online Shopping</p>
          <figure>
            <img
              src="https://idirectpromo.24livehost.com/front/img/icon1.png"
              alt="freedelivery"
            />
            <span>Free delivery</span>
          </figure>
          <figure>
            <img
              src="https://idirectpromo.24livehost.com/front/img/icon2.png"
              alt="returnpolicy"
            />
            <span>14 Days Return</span>
          </figure>
        </div>
      </div>
    </div>
  </div>
</footer>
